### ISSUE TITLE
allow .🥒 as a file extension 

### ISSUE THREAD

**Issue by karl-thomas** [apple/pkl#146]
Feature request: I think it would be nice if we could put a "pickle" (it's really a cucumber) as the file extension, in addition to .pkl. this is similar to mojo files accepting .🔥 as the file extension. https://docs.modular.com/mojo/faq.html#why-does-mojo-have-the-file-extension 

I would also accept any other pickled food emojis.

**Comment by holzensp** [comment]
Yeah, absolutely. Actually, Pkl isn't picky; it already does!

**Comment by karl-thomas** [comment]
<img width="396" alt="Screenshot 2024-02-13 at 7 30 16 PM" src="https://github.com/apple/pkl/assets/23406282/49bc3da5-7d17-4368-be3a-66aefc9b977b">

well I'll be darned, thank you for humoring me, ahahaha. i wonder how angry that makes the nvim plugin, im sure theres some place i can change the file extension.
