### ISSUE TITLE
Active discord invitation link?

### ISSUE THREAD

**Issue by morganhein** [apple/pkl#147]
Is there a place with an active invitation link to the unofficial discord? The only links I can find in this repo are expired.

Thanks!

**Comment by jackkleeman** [comment]
https://discord.gg/Z6cB7BU5CF
sorry about that!

**Comment by morganhein** [comment]
Thanks!

**Comment by jasongwartz** [comment]
@morganhein If you want to share with anyone, we'll also maintain a redirect at: https://pkl-playground.vercel.app/discord-invite
