### ISSUE TITLE
Support fetching secrets from cloud providers

### ISSUE THREAD

**Issue by Clebbie** [apple/pkl#148]
As a Developer I would like to store my application's secrets in my configuration. 

I think we could add this feature with the read() interface. Supporting the cloud platforms could go a long way in making pkl the standard config language it wants to be.

i.e.
read(azvault:some.vault.url)

**Comment by bioball** [comment]
This is possible. To do this, you will need to drive Pkl execution through one of our language bindings.

See:
* https://javadocs.dev/org.pkl-lang/pkl-core/0.25.2/org/pkl/core/resource/ResourceReader.html
* https://pkg.go.dev/github.com/apple/pkl-go@v0.5.3/pkl#ResourceReader
* https://github.com/apple/pkl-swift/blob/main/Sources/PklSwift/Reader.swift#L89

**Comment by Clebbie** [comment]
Got it working in my go project. Ty for the documentation.

**Comment by HT154** [comment]
It's no longer necessary to drive evaluation via the language bindings to do this. The External Readers feature allows extending any Pkl usage (eg. the plain CLI) to allow reading or importing custom URI schemes. You can read more about external readers here: https://pkl-lang.org/main/current/language-reference/index.html. You can see a very basic example of implementing an external reader in golang here: https://pkl-lang.org/go/current/external-readers.html.

**Comment by Clebbie** [comment]
Unfortunately I don’t have access to the code I wrote. I’m looking around to see if I don’t have another example somewhere… no promises though

**Comment by khanakia** [comment]
Yes, i meant that reading directly from the secrets provider may be. I wrote it differently.

Thanks, will check
