### ISSUE TITLE
[FEATURE REQUEST] JavaScript/Node language binding

### ISSUE THREAD

**Issue by codenoid** [apple/pkl#15]

**Comment by jasongwartz** [comment]
If anyone would like to contribute to discussions about Pkl support for Node and TypeScript, please join [the unofficial community Discord](https://discord.gg/5RtS6xA5) and join the conversation in `#bindings-typescript`.

**Comment by holzensp** [comment]
Closing this issue, because of the community initiative this is underway as mentioned by @jasongwartz. It seems best to track this issue on the [`pkl-community` GitHub org](https://github.com/pkl-community).

**Comment by rotu** [comment]
In development at https://github.com/pkl-community/pkl-typescript
