### ISSUE TITLE
Add pkl to GitHub linguist

### ISSUE THREAD

**Issue by 1cedsoda** [apple/pkl#155]
[GitHub Linguist](https://github.com/github-linguist/linguist) can detect the language of a file based on different methods.
It is related to syntax highlighting on GitHub and to generate language statistics inside GitHub repos:

<img width="167" alt="image" src="https://github.com/apple/pkl/assets/29167146/1d1a0380-1bcd-467b-97a0-85f56838f2c4">

I think it's a problem, that there already is [another format called pickle](https://github.com/github-linguist/linguist/blob/559a6426942abcae16b6d6b328147476432bf6cb/lib/linguist/languages.yml#L5206-L5212) with the file extension `.pkl`. Its Python related.

Would be great to add pkl grammar to linguist as it improves code readability on GitHub.

Linguist has quantitative requirements of how many public files of a specific language are hosted on GitHub, before they consider adding it, which might have not been reached yet.

**Comment by bioball** [comment]
It's in the works!

**Comment by darvld** [comment]
Support for Pkl in Linguist is being added by [this PR](https://github.com/github-linguist/linguist/pull/6718). We just noticed this issue was open now so I'm adding a reference here for tracking.

**Comment by HT154** [comment]
Pkl support landed in linguist with https://github.com/github-linguist/linguist/pull/6730 and should be broadly available on github.com now.

**Comment by bioball** [comment]
Closing this one as it's now completed.
