### ISSUE TITLE
Classify GitHub repository with topics

### ISSUE THREAD

**Issue by translatenix** [apple/pkl#244]
From the [GitHub docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics):

> Classifying your repository with topics
>
> To help other people find and contribute to your project, you can add topics to your repository 
> related to your project's intended purpose, subject area, affinity groups, or other important qualities.

Topics can only be added by repo admins. Here are some suggestions:

* language
* programming-language
* configuration
* config
* data
* validation
* functional
* object
* object-oriented
* json
* yaml
* toml
* java
* kotlin

**Comment by translatenix** [comment]
This would only take 5 minutes and can only be done by the team.

**Comment by bioball** [comment]
Added a bunch of your suggestions into our topics. Thanks!
