### ISSUE TITLE
Pkl is not added to PATH

### ISSUE THREAD

**Issue by Arctomachine** [apple/pkl#259]
Installation script only downloads files to local folder, but path to executable is not added to PATH variable.
And so it requires to manually add it or to type full path to executable for cli commands each time, which is not mentioned in installation section https://pkl-lang.org/main/current/pkl-cli/index.html#installation.
But then the first thing mentioned in following usage section is pkl command, which will give error - command not found.

This should be done by script automatically. Also would be good to mention it in docs until it is implemented.

And on side note, why is it not installed into /usr/bin or elsewhere similar?

**Comment by bioball** [comment]
We are working on a homebrew formula that should improve the installation experience for macOS and linux.

PR here: https://github.com/Homebrew/homebrew-core/pull/162857

**Comment by bioball** [comment]
There is now a homebrew formula, which works as an installer for macOS and Linux.
