### ISSUE TITLE
Validation for alias doesn't execute

### ISSUE THREAD

**Issue by miroslav-filipovic** [apple/pkl#264]
I tried following example using 0.25.2 and 0.26.0, but both versions passed with no error.

```
typealias ListingAlias = Listing<Int16>(isDistinctBy((d) -> "not unique"))

temp1 = new ListingAlias {
    1 2 3 4
}

output {
    renderer = new YamlRenderer {}
}
```

As far as I understand, this should fail because `isDistinctBy` wouldn't be unique for each element. 

Using next example I managed to get error:

```
class ListingClass {
    inner: Listing<Int16>(isDistinctBy((d) -> "not unique"))
}

temp2 = new ListingClass {
    inner = new Listing {
        1 2 3 4
    }
}

output {
    renderer = new YamlRenderer {}
}
```

which gave following output

```
Type constraint `isDistinctBy((d) -> "not unique")` violated.

...
```

I think examples are very similar and both should fail, but latter adds more complexity that I'd like to avoid. Am I doing something completely wrong or this is expected? If any of those are the case, let me know and I will close the issue.

**Comment by bioball** [comment]
Right now, Pkl doesn't execute type checks when you do `new Listing<Type>`, or `new Mapping<Type, Type>`. This is a known bug.

To get these type checks to execute, you need to assign the type to your property.

For example:

```
temp1: ListingAlias = new { 1; 2; 3; 4 }
```

**Comment by miroslav-filipovic** [comment]
Nice, thanks!
