### ISSUE TITLE
Cannot import dynamically

### ISSUE THREAD

**Issue by philippemerle** [apple/pkl#290]
I would like to write something like
```
filename = read("prop:source")
template = import(filename)
// Do something on template.
```

But evaluating this produces the following error
```
–– Pkl Error ––
Mismatched input: `filename`. Expected: SLQuote

2 | template = import(filename)
                      ^^^^^^^^
at dynamic_import (file:///.../dynamic_import.pkl, line 2)
```

Is a way to dynamically import a pkl file?

**Comment by stackoverflow** [comment]
Pkl doesn't support dynamic imports, so you can't do that.
The error message can definitely be improved, though. It's not very clear what the error is.

**Comment by philippemerle** [comment]
Thank you for the explanation. This was I thought well.

**Comment by bioball** [comment]
You can emulate "dynamic imports" using [globbed imports](https://pkl-lang.org/main/current/language-reference/index.html#globbed-imports).

For example, you can do:

```
allTemplates = import*("**.pkl")

filename = read("prop:source")

template = allTemplates[filename]
```

Note: globbed imports resolve to a mapping where the keys are the expanded form of the glob. So, the provided `filename` must match something that the glob pattern would expand to.

**Comment by philippemerle** [comment]
Thank for the proposal. I found another way with a shell script:
```sh
#! /bin/sh
uri="file://$(cd "$(dirname "$1")" && pwd -P | sed -- 's/ /%20/g')/$(basename "$1")"
pkl eval - <<EOF
import "$uri" as template
// Do something on template.
EOF
```

**Comment by bioball** [comment]
Closing this, as we do not have any plans to implement this.
