### ISSUE TITLE
`PklProject.exclude` doesn't respect directories

### ISSUE THREAD

**Issue by StefMa** [apple/pkl#318]
in my project I have `examples/` and `tests/` directory.
Obviously I want to exclude those to be packaged.
I can use the following to ignore **the files of these directories**:
```
exclude {
  "examples/**"
  "tests/**"
}
```

However, an empty directory `examples` and `test` is placed into the final `zip`.

I guess this should be avoided.
In case of an directory is empty it shouldn't be part of the final `zip`.

**Comment by bioball** [comment]
Agree; this is an oddity of packaging right now.

**Comment by StefMa** [comment]
If you point me to the direction where to change this I could tackle this
if you want 🙃

**Comment by bioball** [comment]
Right here! https://github.com/apple/pkl/blob/9c1ae0d68392bb24040b2ae8fcc689d4c18186cd/pkl-core/src/main/java/org/pkl/core/project/ProjectPackager.java#L343
