### ISSUE TITLE
Property name with hypen produces error

### ISSUE THREAD

**Issue by tmanternach** [apple/pkl#334]
**What are you trying to achieve?**
I am trying to use pkl to produce a json file that uses hypens in many property names.

**What’s the impact of this bug/feature?**
I cannot use pkl to produce this json file.

`pkl --version` Pkl 0.25.2 (Linux 5.15.0-1050-aws, native)

### Test file
```
test {
        with-hyphen = "test"
}
```

Running `pkl eval -f json file.pkl` produces the following error:

```–– Pkl Error ––
No viable alternative at input `-hyphen =`.
```

### Expected behavior

I would expect `pkl eval -f json file.pkl` to produce the following:

```
{
  "test": {
    "with-hyphen": "test"
  }
}
```

Thank you.

**Comment by translatenix** [comment]
You can use backticks:
```
 `with-hyphen` = "test"
```

**Comment by tmanternach** [comment]
Thank you! I swear I tried everything *but* backticks.

**Comment by StefMa** [comment]
Same applies BTW for keywords.
E.g
```
`function` = 2
```
