### ISSUE TITLE
Why is there no Neovim in pkl.settings.editor?

### ISSUE THREAD

**Issue by uhooi** [apple/pkl#35]
Why is there no Neovim in `Editor` in `pkl.settings` ?
There is a [plugin for Neovim](https://github.com/apple/pkl-neovim) that could be added.

ref: https://pkl-lang.org/package-docs/pkl/0.25.1/settings/

**Comment by holzensp** [comment]
Right now, the `Editor`s are only used to format the URIs of the file references in error messages (producing `idea://path/to/file.pkl` when you use `Idea`, for example. Are there setups where having a clickable link in the terminal to open neovim makes sense? I always use neovim in terminal only and then there's no clicking involved.

If there is, and there is a canonical URI form; happy to take a PR or to follow up at some later stage.

**Comment by uhooi** [comment]
I see...I understand.
Thank you!

**Comment by gibfahn** [comment]
I did the following. I don't need the clickable links, but it means that when I run pkl eval in a Neovim terminal, I can use [gF](https://neovim.io/doc/user/editing.html#gF) to jump to the file at the correct line.

```pkl
amends "pkl:settings"

// Custom URL scheme to make gF work in Neovim.
editor = (Editor) {
  urlScheme = "%{path}:%{line}:%{column}"
}
```
