### ISSUE TITLE
Type parameters in `new Mapping<TypeA, TypeB>`/ `new Listing<Type>` are not checked

### ISSUE THREAD

**Issue by bioball** [apple/pkl#405]
This does not throw, but should:

```
foo = new Listing<Int> {
  "hello"
}
```

In the below, both types should be checked:

```
foo: Listing<Int(isEven)> = new Listing<Int(this > 5)> { 1; 2; 3 }
```

The check should not follow when amended.

This is fine:

```
foo: new Listing<Int> { 1; 2; 3 }

bar = (foo) { "hello" }
```

This should probably be fine too:

```
foo = new Listing<Int> { 1 } { "hello" }
```

**Comment by harryjackson** [comment]
This is just another example. The addition happens and we get 23 but at what point is the type checking meant to happen. Using the IntelliJ plugin I get warnings telling me I'm doing something stupid. 

```bash
foo = new Listing<YamlRenderer> {
  11
}

bar = new Listing<String> {
  22
}

output {
  value = foo[0] + bar[0]
  renderer = new YamlRenderer{}
}
```
output
```bash
33
```

**Comment by translatenix** [comment]
A pragmatic solution would be to allow `x: Listing<A> = new Listing {...}`(*) but not `x = new Listing<A> {...}`. This would reflect the (current) reality that generics aren't reified. It would also encourage users to do the right thing and put type annotations on their properties.

(*) or `x: Listing<A> = (Listing) {...}`

**Comment by holzensp** [comment]
That's less simple than you might think. The generic informs the default / IDE type checking. It's a common pattern to define `Listing`s inline to produce something of a very different type, such as `new Listing<String> { ... }.join(", ")` to produce a `String`.

**Comment by translatenix** [comment]
Dealing with generics is never simple. Regarding your concrete arguments, `Listing.join` is defined for all `Listing`s, not just `Listing<String>`. And perhaps IDEs could infer the element type from the given elements. The default sounds like a problem though.
