### ISSUE TITLE
CODE_OF_CONDUCT.adoc not recognized by GitHub

### ISSUE THREAD

**Issue by translatenix** [apple/pkl#407]
According to `Insights->Community Standards`, this project doesn't have a code of conduct.

Possible solutions:
1. Change `CODE_OF_CONDUCT.adoc` to `CODE_OF_CONDUCT.md`
2. Add `.github/CODE_OF_CONDUCT.md`
3. Define a default code of conduct for Apple projects by adding `CODE_OF_CONDUCT.md` to the `.github` project of the `apple` organization

**Comment by holzensp** [comment]
Since this is not part of our Antora build, there's no reason why it shouldn't just be `.md`.
