### ISSUE TITLE
Rust / Go implementation

### ISSUE THREAD

**Issue by yonas** [apple/pkl#43]
I'd love to hear from anyone interested in writing PKL in Rust (:+1:) or Go.

**Comment by aspizu** [comment]
Can I take this up?

**Comment by yonas** [comment]
> Can I take this up? (Rust to be specific)

Awesome, thanks!

I'll try to setup a bounty if I run into some cash.

**Comment by aspizu** [comment]
What I think I need to do is have the following steps in order to execute a Pkl program:

1. Parse text into AST.
2. Visit the AST to figure out forward-references and imports.
3. Start evaluating expressions and validate that they satisfy their types.
4. Output JSON.

**Comment by holzensp** [comment]
Closing this as better expressed in a Discussion ([discussion already started here](https://github.com/apple/pkl/discussions/49)).
