### ISSUE TITLE
Pkl vs CUE

### ISSUE THREAD

**Issue by pmoust** [apple/pkl#5]
As a user after tackling boilerplate and validation in configuration, I would love a comparison of Pkl vs CUE in the relevant documentation sections.

**Comment by andrewcrook** [comment]
FYI there is also an open discussion #7 for people to share there experiences etc

**Comment by bioball** [comment]
Per @andrewcrook, let's move this to Discussions. Closing this out.

**Comment by pmoust** [comment]
#7 did not exist when this one was raised (it’s #5).
The outcome I was after as a (potential) adopter is what’s described in the OP, but the reply in https://github.com/apple/pkl/discussions/7#discussioncomment-8356664 by @bioball works for me.
Thanks.

(The same has been asked on CUE’s end at https://github.com/cue-lang/cue/issues/2795)
