### ISSUE TITLE
binary serialization

### ISSUE THREAD

**Issue by blacktop** [apple/pkl#581]
It would be awesome if you could add binary serialization to compact the pkl files.  

I started using it in a NEW feature for one of my projects and it is creating very large files ;)

Thanks!

**Comment by bioball** [comment]
WRT large files: are you referring to Pkl source files, or something else?

**Comment by blacktop** [comment]
I might be using `pkl`s not for their intended purpose, but I've enjoying the format so far. 

Here is an example: 
- https://github.com/blacktop/symbolicator/blob/main/kernel/24/xnu.pkl

**Comment by blacktop** [comment]
I prob can .tar.gz etc there files to make them smaller when sending around, but thought; since this is kinda the NEW plist, maybe there'd be a official way to create "bpkl"s similar to bplists to make them as small as possible etc

**Comment by bioball** [comment]
Gotcha. If you're using the pkl-go bindings (seems like you are), you can "bake" Pkl config into their binary representation using [EvaluateExpressionRaw](https://pkg.go.dev/github.com/apple/pkl-go/pkl#Evaluator.EvaluateExpressionRaw).

These bytes can then saved to a file or whatnot, and then be unmarshall'd into the codegen'd structs via [Unmarshal](https://pkg.go.dev/github.com/apple/pkl-go/pkl#Unmarshal).

**Comment by blacktop** [comment]
Awesome! thank you

I don't really understand what the `expr` arg is for here?

https://github.com/apple/pkl-go/blob/4e6500ec73b5cd7665b7f697e4027760302af0c2/cmd/internal/gen-fixtures/gen-fixtures.go#L41

**Comment by blacktop** [comment]
I tried running this:

```go
func BinarySerializeSignature(ctx context.Context, path string) ([]byte, error) {
	evaluator, err := pkl.NewEvaluator(ctx, pkl.PreconfiguredOptions)
	if err != nil {
		return nil, err
	}
	defer func() {
		cerr := evaluator.Close()
		if err == nil {
			err = cerr
		}
	}()
	return evaluator.EvaluateExpressionRaw(ctx, pkl.FileSource(path), "")
}
```
 and this happened 😳

```bash
[ 160]  kernel/
├── [ 128]  23
│   ├── [2.7M]  xnu.pkl
│   └── [2.9M]  xnu.pkl.bin
```

**Comment by bioball** [comment]
Hm, that makes sense I guess. We store information in our binary format that isn't present in source code. You'll probably see a lot of gains by compressing it with gzip or something similar, because there's a lot of repetition in there.

`expr` is the expression to evaluate within the module. If empty, it defaults to the whole module itself (equivalent to `"module"`).

**Comment by blacktop** [comment]
thank you
