### ISSUE TITLE
Regression between 0.26.1 and 0.26.3: properties provided on the commandline with `=` in them are parsed differently

### ISSUE THREAD

**Issue by KushalP** [apple/pkl#630]
This appears to be a regression between `0.26.1` and `0.26.3`. Properties that have an `=` symbol in them are parsed differently.

## Reproduction

```
# 0.26.1
❯ ./pkl-0.26.1 eval -x 'read("prop:foo")' -p foo=bar=baz pkl:base
bar=baz

# 0.26.3
❯ ./pkl-0.26.3 eval -x 'read("prop:foo")' -p foo=bar=baz pkl:base
bar
```

**Comment by holzensp** [comment]
Managed to reproduce. Undoubtedly due to the [fix here](https://github.com/apple/pkl/pull/596).
