### ISSUE TITLE
Read resources default value

### ISSUE THREAD

**Issue by jjuliano** [apple/pkl#637]
I have a template that reads an optional resource.

`
field: String? = read("env:STRING")
`

However, this causes an error when the resource is read because `env:STRING` needs to exist, so I added a default value.

`
field: String? = read("env:STRING") ?? "DEFAULT_STRING"
`

The code above still fails and exits when attempting to read the resource.

**Comment by shurshun** [comment]
This one should work:
`field: String? = read?("env:STRING") ?? "DEFAULT_STRING"`
