### ISSUE TITLE
Error occurs when processing files with Japanese names

### ISSUE THREAD

**Issue by kaniza** [apple/pkl#653]
I was trying to use the `pkl` command to process files with Japanese names. However, an error occurs when attempting to evaluate the file.

#### Information for Bug Report
- **pkl --version**: 
```
Pkl 0.26.3 (macOS 14.4.1, native)
```

- **Complete Error Message**:
```
An unexpected error has occurred. Would you mind filing a bug report?
```

#### Steps to Reproduce
1. Check the version of `pkl`:
    ```shell
    $ pkl --version
    Pkl 0.26.3 (macOS 14.4.1, native)
    ```

2. Create a file `en.pkl` and check the content:
    ```shell
    $ cat en.pkl
    name = ""
    ```

3. Evaluate the file with `pkl`:
    ```shell
    $ pkl eval en.pkl
    name = ""
    ```

4. Copy the file and rename it to a Japanese name:
    ```shell
    $ cp en.pkl 日本語.pkl
    ```

5. Attempt to evaluate the Japanese-named file:
    ```shell
    $ pkl eval 日本語.pkl
    An unexpected error has occurred. Would you mind filing a bug report?
    ```

**Comment by bioball** [comment]
Definitely a bug, thanks for the report!
