### ISSUE TITLE
Cannot search GitHub for “language:pkl”

### ISSUE THREAD

**Issue by translatenix** [apple/pkl#681]
The following search query fails with “unknown language: Pkl”:
`repo:apple/pkl language:Pkl`

The following search query works and finds `.pkl` files:
`repo:apple/pkl language:Pickle`

Not sure what’s going on here, but something is off.

**Comment by bioball** [comment]
Yeah, I'm not really sure; seems like GitHub is a little bugged.

The languages panel correctly identifies Pkl as one of the languages here:

<img width="325" alt="Screenshot 2024-10-13 at 1 26 47 PM" src="https://github.com/user-attachments/assets/4179ca55-9a53-439f-a860-c6f721d77af8">

**Comment by translatenix** [comment]
> The languages panel correctly identifies Pkl as one of the languages here:

Clicking “Pkl 5.7%” is how I discovered the problem.

> Also, nice to hear from you again!

Thanks! Planning to give the Windows support a try.

**Comment by HT154** [comment]
It looks like this is expected (for now) behavior. From https://github.com/github-linguist/linguist/blob/main/docs/troubleshooting.md:

> Note: New languages will not appear in GitHub's search results for some time after the pull request has been merged and the new Linguist release deployed to GitHub.com. This is because GitHub's search uses go-enry for language detection which tends to lag behind Linguist by a few weeks to months. This in turn requires an update to the underlying search code once go-enry is inline with Linguist.

**Comment by bioball** [comment]
Good find! Closing this issue, as it's expected for now, and also there's not much for us to do here.
