### ISSUE TITLE
Does pkl compatible with json? Like yaml as example

### ISSUE THREAD

**Issue by x-0D** [apple/pkl#71]

**Comment by bioball** [comment]
Hi, yes, Pkl can output JSON, and can also parse JSON.

**Comment by x-0D** [comment]
No, i mean, can i create json file and rename it to pkl, does it work as regular pkl file or pkl throw error? If i do this with yaml, yaml should work, because it fully compatible with json and extends it.

**Comment by bioball** [comment]
Ah, no. Pkl's syntax is not compatible with JSON.

**Comment by bioball** [comment]
Closing this out; feel free to start a conversation in https://github.com/apple/pkl/discussions if you want to learn more about Pkl
