### ISSUE TITLE
Allow Paths in http proxy

### ISSUE THREAD

**Issue by rohan-datar** [apple/pkl#720]
Currently, http proxies for only support a `http://<host>:<port>` scheme. 
From the docs:
> When specifying a proxy address, it must have scheme http, and may not contain anything other than a host and port.

Trying to proxy pkl packages through something like [Artifactory Remote Repositories](https://jfrog.com/help/r/jfrog-artifactory-documentation/remote-repositories) does not work as they add a path to the proxy url which is not supported and throws a Java exception when it attempts to resolve.

Allowing proxies to have a `http://<host>:<port>/path/to/proxy` would be very helpful

**Comment by HT154** [comment]
Pkl's HTTP proxy support is for `CONNECT`-based HTTP forward proxies. These work very differently from something like an Artifactory remote repo, which is a read-through caching reverse proxy.

Supporting mirroring via such a reverse proxy requires some additional handling and is being discussed in [SPICE-0002](https://github.com/apple/pkl-evolution/pull/4).

**Comment by bioball** [comment]
Closing this, but feel free to follow or contribute to SPICE-0002 for your use case!
