### ISSUE TITLE
Pkldoc: If `DocPackageInfo.version` is not semver version core the Module is not visible in overview

### ISSUE THREAD

**Issue by StefMa** [apple/pkl#755]
I just noticed that in case the `DocPackageInfo.version` is **not a [semver core version](https://semver.org/)** (MAJOR.MINOR.PATCH), then the Module will not be displayed in the overview:
![Screenshot 2024-10-30 at 1 13 42 PM](https://github.com/user-attachments/assets/5b2ac12b-540f-427f-9d50-93bbc23f43a6)

The page is just empty ☝️ 

However, the files are beeing created.
Going to `URL.com/com.github` (`com.github` is the `DocPackageInfo.name`), the pre-version is displayed correctly:
![Screenshot 2024-10-30 at 1 15 13 PM](https://github.com/user-attachments/assets/24453205-cf5c-4586-bf12-06dcac7680ae)

Right now I'm not sure if this is an bug (Module is not displayed) or intented behaviour that should be documented.

**Comment by bioball** [comment]
pkldoc omits pre-release packages from the index page. So, given the current logic, this is expected behavior.
