### ISSUE TITLE
Support cloning the project on Windows

### ISSUE THREAD

**Issue by translatenix** [apple/pkl#99]
This is the first step in #20 and critical to unlock outside contributions.

**Comment by translatenix** [comment]
Is there a timeline to fix this? Developing on WSL is really painful. Gradle and esp. IntelliJ are extremely slow, and important IntelliJ features such as showing the JDK source code don't work.
I think fixing this might require changing the package cache file layout (no `:` character in filenames).

**Comment by translatenix** [comment]
@bioball Windows support is very important to me. I'd be willing to work on this first step, but I'd need some guidance wrt. changing the cache file layout.

**Comment by bioball** [comment]
How about we precent-encode them?

According to [their docs](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions), these characters are reserved:

* < (less than)
* > (greater than)
* : (colon)
* " (double quote)
* / (forward slash)
* \ (backslash)
* | (vertical bar or pipe)
* ? (question mark)
* \* (asterisk)

Forward slash is also reserved on macOS and Linux, so we don't need to worry about encoding them (Pkl filenames cannot contain forward slashes, and URI forward slashes are equated to path separators).

For Windows only, it probably makes sense to percent-encode all other characters. Or, are there other encodings that people use?

Here's some literature:

https://stackoverflow.com/questions/1184176/how-can-i-safely-encode-a-string-in-java-to-use-as-a-filename
https://stackoverflow.com/questions/1077935/will-urlencode-fix-this-problem-with-illegal-characters-in-file-names-c

**Comment by translatenix** [comment]
Don't we want the exact same layout across operating systems? Seems desirable for portability/tooling/etc.
Gradle's cache used to be non-portable, and it caused a lot of frustration.
https://github.com/gradle/gradle/issues/1338

**Comment by bioball** [comment]
I can see wanting that, especially if you are using the cache dir as a way to vendor dependencies in a repo.

In that case, it might make more sense to think of this as a separate problem from writing file paths with `-o` or `-m`. In those cases, it'd be surprising if `-o "foo:bar.pkl"` somehow mangled that output file on linux/macOS.

In that case, maybe it makes the most sense to always percent encode those characters when writing to the cache dir.

**Comment by translatenix** [comment]
Is mangling required for -o/-m? Can’t `-o "foo:bar.txt"` just fail on Windows? Another option would be to make it fail everywhere (“non-portable output file”).

**Comment by translatenix** [comment]
> What does Windows do right now if you try to create a filename with a reserved character?

PowerShell:
```
echo "hello" >> foo:bar.txt
Out-File: Cannot find drive. A drive with the name 'foo' does not exist.
```
```
echo "hello" >> $home\foo:bar.txt   # creates a file named "foo", but it's empty
```

Java
```
jshell> new File("foo:bar.txt").createNewFile()   //  creates a file named "foo"
```
```
jshell> Files.createFile(Path.of("foo:bar.txt"))
|  Exception java.nio.file.InvalidPathException: Illegal char <:> at index 3: foo:bar.txt
```

**Comment by translatenix** [comment]
I assume the package URL -> file path conversion should be unique, to rule out name collisions. Does it also need to be reversible?

**Comment by bioball** [comment]
Yeah, ideally reversible, which is why percent-encoding seems like a good choice here.

**Comment by mitchcapper** [comment]
> `echo "hello" > $home\foo:bar.txt `
> `jshell> new File("foo:bar.txt").createNewFile()   // creates a file named "foo"`

To note, the colon here is only kind of an invalid character.  Really what you are doing is writing to alternate data streams.   This is why the file can appear but is 'empty'.   For details: https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/c54dec26-1551-4d3a-a0ea-4fa40f848eb3

This is just one character but will be slightly different than other path characters that are truly invalid (in terms of if/what errors thrown).

**Comment by bioball** [comment]
Hm... this impacts pkldoc too. This means that generated pkldoc websites should also use percent encoding, otherwise we can't write directories or filenames onto Windows.

@mitchcapper good to know. I don't think that changes the fact that we should encode these characters.

**Comment by mitchcapper** [comment]
> I don't think that changes the fact that we should encode these characters.

Right, should certainly not be on the whitelist as not valid as path only some apis for the alt stream access.

**Comment by bioball** [comment]
WRT encoding: 
* Scala does not do any encoding; generating scaladoc will error if a class name contains a reserved character.
* Kotlin's Dokka wraps reserved characters in square brackets, then the character code inside. For example, `:` becomes `[58]`.
* Doesn't seem like Swift's DocC has figured out a solution here yet: https://forums.swift.org/t/docc-colons-in-filenames/57917/27

**Comment by bioball** [comment]
Maybe we can copy Dokka. We can simply escape verbatim `[` with `[[`. Multiple `[` literals would just be double the amount of `[`.

I don't think we need a special handler for `]`.

| literal | encoded |
| --- | --- |
| `foo:bar` | `foo[58]bar` |
| `foo[58]bar` | `foo[[58]bar` |
| `foo[[` | `foo[[[[` |
| `foo[:bar` | `foo[[[58]bar` |

One downside is that we have four bytes to represent one byte, which might be a problem with URL addresses. But this is an edge case that maybe we can live with.

**Comment by bioball** [comment]
Proposal here: https://github.com/apple/pkl-evolution/pull/3

**Comment by bioball** [comment]
This works now per https://github.com/apple/pkl/pull/489
